name: limitless_flutter
description: "The frontend of limitless developed in Flutter"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  dynamic_color: ^1.8.1
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  supabase_flutter: ^2.10.3
  flutter_dotenv: ^6.0.0
  google_fonts: ^6.3.2
  animations: ^2.1.0
  logger: ^2.6.2
  country_picker: ^2.0.27
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/background/
    - config/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/limitless-icon.png
  web:
    generate: true
    image_path: assets/images/limitless-icon.png
    background_color: "#000000"
    theme_color: #000000""
